name: windows

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} -p:Instruction_Set=AdvancedVectorExtensions2

    - name: Upload a full build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: full artifacts-b${{ github.run_number }}
        path: .
